import './globals.css';
import 'nextra-theme-docs/style.css';
import type { Metadata } from 'next';
import { Footer, Layout, Navbar } from 'nextra-theme-docs';
import { getPageMap } from 'nextra/page-map';
import { Banner, Head } from 'nextra/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const banner = <Banner storageKey="some-key">Nextra 4.0 is released 🎉</Banner>;
const footer = <Footer>MIT {new Date().getFullYear()} © Nextra.</Footer>;
const navbar = <Navbar logo={<b>Linkeyss</b>} />;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      dir="ltr"
      suppressHydrationWarning>
      <body className={` antialiased`}>
        <Layout
          sidebar={{}}
          banner={banner}
          navbar={navbar}
          pageMap={await getPageMap()}
          footer={footer}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
